"""Initial schema

Revision ID: 232377f9d435
Revises: 
Create Date: 2026-07-03 20:04:07.671997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '232377f9d435'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('github_repo', sa.String(), nullable=False),
    sa.Column('owner_github_id', sa.BigInteger(), nullable=False),
    sa.Column('api_token_hash', sa.String(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_repo')
    )
    op.create_table('strategies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('soroban_type', sa.String(), nullable=False),
    sa.Column('crate_version', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'crate_version', name='strategies_name_crate_version_key')
    )
    op.create_table('fuzz_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('commit_sha', sa.String(), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('iterations', sa.BigInteger(), nullable=False),
    sa.Column('coverage_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fuzz_runs_commit_sha', 'fuzz_runs', ['commit_sha'], unique=False)
    op.create_index('idx_fuzz_runs_project_id', 'fuzz_runs', ['project_id'], unique=False)
    op.create_table('crashes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fuzz_run_id', sa.UUID(), nullable=False),
    sa.Column('target_fn', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('dedup_hash', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reproducer_path', sa.String(), nullable=True),
    sa.Column('first_seen_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('low', 'medium', 'high', 'critical')", name='crashes_severity_check'),
    sa.CheckConstraint("status IN ('open', 'acknowledged', 'fixed', 'wontfix')", name='crashes_status_check'),
    sa.ForeignKeyConstraint(['fuzz_run_id'], ['fuzz_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_crashes_dedup', 'crashes', ['fuzz_run_id', 'dedup_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_crashes_dedup', table_name='crashes')
    op.drop_table('crashes')
    op.drop_index('idx_fuzz_runs_project_id', table_name='fuzz_runs')
    op.drop_index('idx_fuzz_runs_commit_sha', table_name='fuzz_runs')
    op.drop_table('fuzz_runs')
    op.drop_table('strategies')
    op.drop_table('projects')
    # ### end Alembic commands ###
